# -*- coding: utf-8 -*-
"""
Convert Minecraft 1.9 to 1.12.2 blocks to similar blocks
in appearance as a Minecraft 1.8 replacement
"""

CHUNK_HEIGHT = 254
CHUNK_LENGTH = 16

def get_block_replacement(b):
    replacements = {
        "End Rod": "",
        "Chrous Plant": "",
        "Chrous Flower": "",
        "Purpur Block": "",
        "Purpur Pilar": "",
        "Purpur Stairs": "",
        "Purpur Slab": "",
        "End Stone Bricks": "",
        "Magma Block": "",
        "Nether Wart Block": "",
        "Red Nether Brick": "",
        "Bone Block": "",
        "Observer": "",
        "While Shulker Box": "",
        "Orange Shulker Box": "",
        "Magenta Shulker Box": "",
        "Light Blue Shulker Box": "",
        "Yellow Shulker Box": "",
        "Lime Shulker Box": "",
        "Pink Shulker Box": "",
        "Grey Shulker Box": "",
        "Light Grey Shulker Box": "",
        "Cyan Shulker Box": "",
        "Purple Shulker Box": "",
        "Blue Shulker Box": "",
        "Brown Shulker Box": "",
        "Green Shulker Box": "",
        "Red Shulker Box": "",
        "Black Shulker Box": "",
        "While Glazed Terracotta": "",
        "Orange Glazed Terracotta": "",
        "Magenta Glazed Terracotta": "",
        "Light Glazed Terracotta": "",
        "Yellow Glazed Terracotta": "",
        "Lime Glazed Terracotta": "",
        "Pink Glazed Terracotta": "",
        "Grey Glazed Terracotta": "",
        "Light Glazed Terracotta": "",
        "Cyan Glazed Terracotta": "",
        "Purple Glazed Terracotta": "",
        "Blue Glazed Terracotta": "",
        "Brown Glazed Terracotta": "",
        "Green Glazed Terracotta": "",
        "Red Glazed Terracotta": "",
        "Black Glazed Terracotta": "",
        "White Concrete": "",
        "Orange Concrete": "",
        "Magenta Concrete": "",
        "Light Concrete": "",
        "Yellow Concrete": "",
        "Lime Concrete": "",
        "Pink Concrete": "",
        "Grey Concrete": "",
        "Light Concrete": "",
        "Cyan Concrete": "",
        "Purple Concrete": "",
        "Blue Concrete": "",
        "Brown Concrete": "",
        "Green Concrete": "",
        "Red Concrete": "",
        "Black Concrete": "",
        "White Concrete Powder": "",
        "Orange Concrete Powder": "",
        "Magenta Concrete Powder": "",
        "Light Concrete Powder": "",
        "Yellow Concrete Powder": "",
        "Lime Concrete Powder": "",
        "Pink Concrete Powder": "",
        "Grey Concrete Powder": "",
        "Light Concrete Powder": "",
        "Cyan Concrete Powder": "",
        "Purple Concrete Powder": "",
        "Blue Concrete Powder": "",
        "Brown Concrete Powder": "",
        "Green Concrete Powder": "",
        "Red Concrete Powder": "",
        "Black Concrete Powser": "",
        "White Bed": "",
        "Orange Bed": "",
        "Magenta Bed": "",
        "Light Bed": "",
        "Yellow Bed": "",
        "Lime Bed": "",
        "Pink Bed": "",
        "Grey Bed": "",
        "Light Bed": "",
        "Cyan Bed": "",
        "Purple Bed": "",
        "Blue Bed": "",
        "Brown Bed": "",
        "Green Bed": "",
        "Red Bed": "",
        "Black Bed": ""
    }
